### ISSUE TITLE
Menu déroulant ne se referme pas au clic 

### ISSUE THREAD

**Issue by MarieVerinaud** [Ryfacto/ryfacto.fr#1]
![3833563c-b82d-408a-b6cb-e953c924ebb9](https://user-images.githubusercontent.com/18597094/32659352-a99652e0-c61e-11e7-960b-7250a27aa5c8.png)
Le menu déroulant ne se referme pas après clic sur une catégorie.

**Comment by nverinaud** [comment]
Fixed 😉
